services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/debian/CryptoTrackerBot/data:/app/data
      - /etc/localtime:/etc/localtime
    restart: always
    logging:
      driver: "json-file"
    environment:
      - PYTHONUNBUFFERED=1