services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/pi/CryptoTrackerBot/data:/home/telegram/data
    restart: always
    environment:
      - TELEGRAM_BOT_API